### ISSUE TITLE
Consider changing default value of input argument in model.plot() in spatial.py

### ISSUE THREAD

**Issue by bjorntsv** [knutankv/koma#3]
In spatial.py, consider changing the default value of the input argument _plot_faces_ to **False** from **True** in the class _model_ method _plot_ (line 481), or include an if-else statement. The code throws an error of "TypeError: Indices must be either a mask or an integer array-like" if no faces are defined, which can be confusing if the model is not intended to have any face elements but only line elements.

Thanks for a great work with this package!

**Comment by knutankv** [comment]
Thanks for the suggestion.

I have added a check in `koma.spatial.Model.plot` in version 1.3.4 that ensures that the requested elements are present before plotting them. (Default values for `plot_faces` and `plot_lines` are kept)
